---
- name: Configure Docker APT repository   
  hosts: localhost
  become: yes  # Use 'become' to run commands with sudo

  tasks:
    - name: Add Docker APT repository
      shell: printf 'deb https://download.docker.com/linux/debian bookworm stable' | sudo tee /etc/apt/sources.list.d/docker-ce.list
      changed_when: false  # Avoid marking this task as changed even if it doesn't change anything

    - name: Download Docker GPG key
      shell: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/docker-ce-archive-keyring.gpg
      changed_when: false  # Avoid marking this task as changed even if it doesn't change anything
    - name: apt update
      shell: apt update
