---
- name: Configure Docker repository and update apt
  hosts: localhost
  become: yes  # Use 'become' to run commands with sudo

  tasks:
    - name: Configure Docker repository
      shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo $VERSION_CODENAME) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      changed_when: false  # Mark this task as not changed to avoid running handlers

    - name: Update apt cache
      apt:
        update_cache: yes
