---
- name: Clone Git Repositories in /opt/
  hosts: localhost 

  tasks:
    - name: Clone Certify repository
      git:
        repo: https://github.com/GhostPack/Certify.git
        dest: /opt/Certify

    - name: Clone Certipy repository
      git:
        repo: https://github.com/ly4k/Certipy.git
        dest: /opt/Certipy

    - name: Clone Bashfuscator repository
      git:
        repo: https://github.com/Bashfuscator/Bashfuscator.git
        dest: /opt/Bashfuscator

    - name: Clone Chisel repository
      git:
        repo: https://github.com/jpillora/chisel.git
        dest: /opt/chisel

    - name: Clone Dirhunt repository
      git:
        repo: https://github.com/Nekmo/dirhunt.git
        dest: /opt/dirhunt

    - name: Clone DonPAPI repository
      git:
        repo: https://github.com/login-securite/DonPAPI.git
        dest: /opt/DonPAPI

    - name: Clone EyeWitness repository
      git:
        repo: https://github.com/RedSiege/EyeWitness.git
        dest: /opt/EyeWitness

    - name: Clone Aquatone repository
      git:
        repo: https://github.com/michenriksen/aquatone.git
        dest: /opt/aquatone

    - name: Clone Ligolo-ng repository
      git:
        repo: https://github.com/nicocha30/ligolo-ng.git
        dest: /opt/ligolo-ng
        
    - name: Build Ligolo-ng agent
      command: go build -o /opt/ligolo-ng/agent /opt/ligolo-ng/cmd/agent/main.go
      args:
        chdir: /opt/ligolo-ng

    - name: Build Ligolo-ng proxy
      command: go build -o /opt/ligolo-ng/proxy /opt/ligolo-ng/cmd/proxy/main.go
      args:
        chdir: /opt/ligolo-ng

    - name: Clone Linikatz repository
      git:
        repo: https://github.com/CiscoCXSecurity/linikatz.git
        dest: /opt/linikatz

    - name: Clone logrotten repository
      git:
        repo: https://github.com/whotwagner/logrotten.git
        dest: /opt/logrotten

    - name: Clone noPac repository
      git:
        repo: https://github.com/Ridter/noPac.git
        dest: /opt/noPac

    - name: Clone pspy repository
      git:
        repo: https://github.com/DominicBreuker/pspy.git
        dest: /opt/pspy

    - name: Clone pypykatz repository
      git:
        repo: https://github.com/skelsec/pypykatz.git
        dest: /opt/pypykatz

    - name: Clone statistically-likely-usernames repository
      git:
        repo: https://github.com/insidetrust/statistically-likely-usernames.git
        dest: /opt/statistically-likely-usernames

    - name: Clone subbrute repository
      git:
        repo: https://github.com/TheRook/subbrute.git
        dest: /opt/subbrute

    - name: Clone username-anarchy repository
      git:
        repo: https://github.com/urbanadventurer/username-anarchy.git
        dest: /opt/username-anarchy

    - name: Clone XSStrike repository
      git:
        repo: https://github.com/s0md3v/XSStrike.git
        dest: /opt/XSStrike

    - name: Clone XXEinjector repository
      git:
        repo: https://github.com/enjoiz/XXEinjector.git
        dest: /opt/XXEinjector

    - name: Clone ADRecon repository
      git:
        repo: https://github.com/adrecon/ADRecon.git
        dest: /opt/ADRecon

    - name: Clone SharpHound repository
      git:
        repo: https://github.com/BloodHoundAD/SharpHound.git
        dest: /opt/SharpHound

    - name: Clone mimikatz repository
      git:
        repo: https://github.com/ParrotSec/mimikatz.git
        dest: /opt/mimikatz

    - name: Clone Invoke-TheHash repository
      git:
        repo: https://github.com/Kevin-Robertson/Invoke-TheHash.git
        dest: /opt/Invoke-TheHash

    - name: Clone Group3r repository
      git:
        repo: https://github.com/Group3r/Group3r.git
        dest: /opt/Group3r

    - name: Clone Inveigh repository
      git:
        repo: https://github.com/Kevin-Robertson/Inveigh.git
        dest: /opt/Inveigh

    - name: Clone juicy-potato repository
      git:
        repo: https://github.com/ohpe/juicy-potato.git
        dest: /opt/juicy-potato

    - name: Clone RoguePotato repository
      git:
        repo: https://github.com/antonioCoco/RoguePotato.git
        dest: /opt/RoguePotato

    - name: Clone PowerSploit repository
      git:
        repo: https://github.com/PowerShellMafia/PowerSploit.git
        dest: /opt/PowerSploit

    - name: Clone PrintSpoofer repository
      git:
        repo: https://github.com/itm4n/PrintSpoofer.git
        dest: /opt/PrintSpoofer

    - name: Clone Rubeus repository
      git:
        repo: https://github.com/GhostPack/Rubeus.git
        dest: /opt/Rubeus

    - name: Clone Snaffler repository
      git:
        repo: https://github.com/SnaffCon/Snaffler.git
        dest: /opt/Snaffler

    - name: Clone nc.exe repository
      git:
        repo: https://github.com/int0x33/nc.exe.git
        dest: /opt/nc.exe

    - name: Copy files from foo to bar
        copy: remote_src=True src=./Kali_install/windows/ dest=/opt/windows/
    - name: Remove old files foo
        file: path=./Kali_Install/windows/ state=absent
        
