---
- name: "Installing VSCode + Extenstions"
  hosts: localhost
  connection: local
  roles:
    - role: gantsign.visual-studio-code
      users:
        - username: "{{ ansible_user_id }}" 
          visual_studio_code_extensions:
            - streetsidesoftware.code-spell-checker
            - snyk-security.snyk-vulnerability-scanner
            - ms-python.python
            - DEVSENSE.phptools-vscode
